apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eu-test

generatorOptions:
  disableNameSuffixHash: true

resources:
  - ../../postgresql
  - ../../app

commonLabels:
  app: golang-reference-project

configMapGenerator:
  - name: config.yaml
    files:
      - config.yaml=config.eu-test.yaml

patchesStrategicMerge:
  - postgresql.deployment.yaml
  - app.deployment.yaml