version: '3.9'

networks:
  default:
    name: golang-reference-project

services:
  postgresql:
    image: postgres:14.2
    container_name: postgresql
    hostname: postgresql
    environment:
      POSTGRES_DB: dev_db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - '5432:5432'