openapi: "3.0.3"
info:
  version: 0.1.2
  title: Orders API
paths:
  /api/orders:
    get:
      summary: Get all orders
      tags:
        - orders
      responses:
        200:
          description: A array of orders
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/orders"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
    post:
      summary: Create a order
      tags:
        - orders
      responses:
        201:
          description: Null Response
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /api/orders/{orderId}:
    get:
      summary: Info for a specific order
      tags:
        - orders
      parameters:
        - name: orderId
          in: path
          required: true
          description: The id of the order to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/order"
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
components:
  schemas:
    order:
      type: object
      required:
        - order_id
        - creation_date
        - status
        - items
      properties:
        order_id:
          type: string
          example: I3xXiIqbP92-NONE-DEV-Ui*8i0kFHcA
        creation_date:
          type: string    
          format: date-time
        status:
          $ref: "#/components/schemas/status"
        items:
          type: array
          items:
            $ref: "#/components/schemas/item"
    status: 
      type: string
      enum:
        - order_completed
        - order_canceled
        - order_in_progress
        - order_placed
    orders:
      type: array
      items:
        $ref: "#/components/schemas/order"
    item: 
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: "banana"
    error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          example: 9001
        message:
          type: string
          example: panic it's over 9000