apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      service: postgresql
  template:
    metadata:
      labels:
        service: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:14.2
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          args:
            - -c
            - log_statement=all
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: postgresql-credentials
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: postgresql-credentials