# Global config
region: EU
environment: TEST

# Server config
server:
  port: 8080
  timeout:
    read: 10
    write: 10
    idle: 10

# Logger config
logger:
  level: INFO

# Database config
database:
  host: postgresql.eu-test
  port: 5432
  user: "InFutureNeedToInjectEnvVar"
  password: "SdzA7vp6GPPUNRjnelSs"
  database: "test_db"
