apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
        - name: app
          image: ghcr.io/valentinlutz/golang-reference-project
          imagePullPolicy: Always
          env:
            - name: POSTGRESQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgresql-credentials
                  key: username
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-credentials
                  key: password
          volumeMounts:
            - mountPath: /app/config/
              name: config-volume
      volumes:
        - name: config-volume
          configMap:
            name: config.yaml
