apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      service: app
  template:
    metadata:
      labels:
        service: app
    spec:
      containers:
        - name: app
          image: ghcr.io/valentinlutz/golang-reference-project
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              scheme: HTTPS
              port: 8080
              path: /api/status/health
          livenessProbe:
            httpGet:
              scheme: HTTPS
              port: 8080
              path: /api/status/health
          env:
            - name: POSTGRESQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgresql-credentials
                  key: username
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-credentials
                  key: password
          volumeMounts:
            - name: config-volume
              mountPath: /app/config/
              readOnly: true
      volumes:
        - name: config-volume
          projected:
            sources:
              - configMap:
                  name: config.yaml
              - secret:
                  name: tls-certificate
