apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: postgresql-credentials
    literals:
      - username=InFutureNeedToInjectEnvVar
      - password=SdzA7vp6GPPUNRjnelSs
  - name: tls-certificate
    files:
      - cert.crt=none-dev.crt
      - cert.key=none-dev.key

resources:
  - app.deployment.yaml
  - app.service.yaml
