name: default-workflow

on:
  push:

jobs:

  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.create.outputs.version }}
    steps:
      - name: Create project version
        id: create
        run: echo "::set-output name=version::$(date +"%y.%m.%d.%H%M%S")"

  build:
    runs-on: ubuntu-latest
    needs: version
    env:
      DOCKER_REGISTRY: ghcr.io
      DOCKER_REPOSITORY: valentinlutz
      VERSION: ${{ needs.version.outputs.version }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up GO
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.1

      - name: Install oapi-codegen
        run: go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@v1.10.1

      - name: Run unit tests
        run: make test.unit

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46.1
          working-directory: app
          skip-pkg-cache: true

      - name: Build the container images
        run: make docker.build

      - name: Login to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push the container images
        run: make docker.push
