name: GO

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up GO
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.1

      - name: Install oapi-codegen
        run: go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@v1.10.1

      - name: Unit Test
        run: make test.unit
